package teodor.flavor_chaser_android_app.utils;

public class GeneralInfo {

    public static final String RETROFIT_BASE_URL = "http://192.168.100.51:8080";
    public static final String SHARED_PREFERENCES_FILENAME = "MAIN_SHARED_PREFERENCES_FILE";
    public static final String SHARED_PREFERENCES_USER_EMAIL_KEY = "CURRENT_USER_EMAIL";
    public static final String PASS_USER_REDIRECTACTIVITY_TO_MAINACTIVITY = "USER_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_COMPANIES_REDIRECTACTIVITY_TO_MAINACTIVITY = "COMPANIES_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_FLAVORS_REDIRECTACTIVITY_TO_MAINACTIVITY = "FLAVORS_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_FLAVORS_CATEGORIES_REDIRECTACTIVITY_TO_MAINACTIVITY = "FLAVORS_CATEGORIES_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_FLAVORS_WARNINGS_REDIRECTACTIVITY_TO_MAINACTIVITY = "FLAVORS_WARNINGS_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_INGREDIENTS_IN_STASH_REDIRECTACTIVITY_TO_MAINACTIVITY = "INGREDIENTS_IN_STASH_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_RATINGS_REDIRECTACTIVITY_TO_MAINACTIVITY = "RATINGS_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_RECIPES_REDIRECTACTIVITY_TO_MAINACTIVITY = "RECIPES_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_RECIPE_FLAVORS_REDIRECTACTIVITY_TO_MAINACTIVITY = "RECIPE_FLAVORS_REDIRECTACTIVITY_TO_MAINACTIVITY";
}
