package teodor.flavor_chaser_android_app.utils;

public class GeneralInfo {

    public static final String RETROFIT_BASE_URL = "http://192.168.100.51:8080";
    public static final String SHARED_PREFERENCES_FILENAME = "MAIN_SHARED_PREFERENCES_FILE";
    public static final String SHARED_PREFERENCES_USER_EMAIL_KEY = "CURRENT_USER_EMAIL";
    public static final String PASS_USER_REDIRECTACTIVITY_TO_MAINACTIVITY = "USER_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_FLAVORS_REDIRECTACTIVITY_TO_MAINACTIVITY = "FLAVORS_REDIRECTACTIVITY_TO_MAINACTIVITY";
    public static final String PASS_COMPANIES_REDIRECTACTIVITY_TO_MAINACTIVITY = "COMPANIES_REDIRECTACTIVITY_TO_MAINACTIVITY";
}
