create table companies (id bigint not null auto_increment, name varchar(255), website varchar(255), primary key (id)) engine=MyISAM;
create table flavor_categories (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=MyISAM;
create table flavor_warnings (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=MyISAM;
create table flavors (id bigint not null auto_increment, description varchar(255), name varchar(255), flavor_category_id bigint, company_id bigint, flavor_warning_id bigint, primary key (id)) engine=MyISAM;
create table ingredients_in_stash (id bigint not null auto_increment, current_quantity_in_ml float(53), price decimal(38,2), purchase_date date, type varchar(255), flavor_id bigint, user_id bigint, primary key (id)) engine=MyISAM;
create table ratings (id bigint not null auto_increment, score float(23), recipe_id bigint, flavor_id bigint, primary key (id)) engine=MyISAM;
create table recipe_flavors (id bigint not null auto_increment, percentage float(53), flavor_id bigint, recipe_id bigint, primary key (id)) engine=MyISAM;
create table recipes (id bigint not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=MyISAM;
create table stash_flavors (id bigint not null auto_increment, current_quantity float(53), price decimal(38,2), purchase_date date, flavor_id bigint, primary key (id)) engine=MyISAM;
create table users (id bigint not null auto_increment, creation_date datetime, email_address varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), primary key (id)) engine=MyISAM;
create table users_recipes (id bigint not null auto_increment, user_recipe_relation varchar(255), recipe_id bigint, user_id bigint, primary key (id)) engine=MyISAM;
alter table flavors add constraint FKe9jrfqq3eem40gi29nlaa4owt foreign key (flavor_category_id) references flavor_categories (id);
alter table flavors add constraint FK88lquql5826rlofa52r79pfxj foreign key (company_id) references companies (id);
alter table flavors add constraint FKbcr46c6iyqvpysqd9g9vr3wrv foreign key (flavor_warning_id) references flavor_warnings (id);
alter table ingredients_in_stash add constraint FKgr6ynxhfs5yi96ibdrnpmsjlb foreign key (flavor_id) references flavors (id);
alter table ingredients_in_stash add constraint FKpdyqwr4k1cfb603v8q3uex78o foreign key (user_id) references users (id);
alter table ratings add constraint FK12o4ql2wkhay4u9qw2ashmho7 foreign key (recipe_id) references recipes (id);
alter table ratings add constraint FK9t0800x6d2wnsmqpwb11jmxun foreign key (flavor_id) references flavors (id);
alter table recipe_flavors add constraint FKk9ettvofwbe6k7yd4bmb8vxlf foreign key (flavor_id) references flavors (id);
alter table recipe_flavors add constraint FKr6h4xiiyo226w9e5fgwg8wgrj foreign key (recipe_id) references recipes (id);
alter table stash_flavors add constraint FKeey0ydv0b0ns2m7khl0255pbm foreign key (flavor_id) references flavors (id);
alter table users_recipes add constraint FKft9f6nhdnlm9lq3plsb1274nn foreign key (recipe_id) references recipes (id);
alter table users_recipes add constraint FK6st0jnhyq1lmru9olv90i4mv9 foreign key (user_id) references users (id);
